DROP TABLE users CASCADE;
DROP TABLE languages CASCADE;
DROP TABLE decks CASCADE;
DROP TABLE cards CASCADE;
DROP TABLE scores CASCADE;
DROP TABLE backs CASCADE;
DROP TABLE sets CASCADE;
DROP TABLE set_cards CASCADE;